### ISSUE TITLE
Lighting issue in base. Light blocks not emitting light.[BUG]

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [mahjerion/Craft-to-Exile-2-Resolution#22]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 2.13.2c
 - World Type: Official Tristram server
 - RAM Allocation: 8GB

**Describe the bug**
After one of the recent updates, a single chunk in my base refuses to emit light. Torches don't work, neither do redstone lamps. Breaking and re-placing all light sources temporarily fixes the light, but after leaving the area and returning, the light is set back to 0. Light level is not just visual, mobs spawn in the area.

**To Reproduce**
Load chunk.

**Expected behavior**
A light value of above 0.

**Additional Information (screen shots, etc.)**

https://i.imgur.com/Ofxz2Uw.png
https://i.imgur.com/QNXYgjJ.png
https://i.imgur.com/b7VukvD.jpeg

**Comment by IAA-ShRaPNeL** [comment]
Found this Mojang ticket with a solution https://bugs.mojang.com/browse/MC-142134

**Comment by mahjerion** [comment]
wrong modpack btw x) but yeah seems like it was solved in server chat
