### ISSUE TITLE
[BUG] Die and client stuck on Dying screen and couple secs client crashes

### ISSUE THREAD

**Issue by Ralance** [mahjerion/Craft-to-Exile-2-Resolution#23]
**Technical Specs (please complete the following information):**
 - - Craft to Exile Resolution 0.1.0
 - World Type Multiplayer Dedicated server hosting
 - RAM Allocation 4GB

**Describe the bug**
I died to TNT explosion and then I'm just stuck on your dead screen and I can do nothing till it crashes the client.

**To Reproduce**
I think it's almost sometimes random, You happened to die.

**Expected behavior**

**Additional Information (screen shots, etc.)**
https://pastebin.com/EjRecDep

**Comment by Ralance** [comment]
I tp my friend that kept crashing to the explosion and he crashed me as soon as he tped to me. 
https://pastebin.com/FKze3Wnc

**Comment by Ralance** [comment]
So it seems that if you die during the loading terrain/loading into the server, it will crash your Minecraft client.

**Comment by Ralance** [comment]
So there is a small fix I did to fix it.  /gamerule doImmediateRespawn true 
You'll do immediate respawn

**Comment by mahjerion** [comment]
should be fixed, thanks
