### ISSUE TITLE
[BUG] Server crash when exploring

### ISSUE THREAD

**Issue by Ralance** [mahjerion/Craft-to-Exile-2-Resolution#24]
**Technical Specs (please complete the following information):**
 - Craft to Exile Resolution 0.1 BETA
 - World Type Multiplayer
 - RAM Allocation 4GB

**Describe the bug**
Exploring the world and crashes server. Boots up fine.

**To Reproduce**
exploring the world

**Expected behavior**

**Additional Information (screen shots, etc.)**
https://pastebin.com/tfRMM49p

**Comment by mahjerion** [comment]
disabled meerkats for this, thanks
