### ISSUE TITLE
[BUG] Mass illager spawns around illager outposts BETA 0.1.1

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#28]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.1
 - World Type Multiplayer
 - RAM Allocation 9GB
 
**Describe the bug**
A very large amount of illagers spawn around illager outposts

**To Reproduce**
1. Go to illager outpost
2. Watch them spawn

**Expected behavior**
maybe 1/10 of the current amount of illagers

**Additional Information (screen shots, etc.)**
![2021-11-05_01 52 01](https://user-images.githubusercontent.com/36768970/140440227-b3143c0f-0e50-42b4-b998-c05505f4e125.png)

**Comment by mahjerion** [comment]
should be fixed next update
