### ISSUE TITLE
[BUG] Spawners still drop age of exile stuff when broken BETA 0.1.1

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#29]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.1
 - World Type Multiplayer
 - RAM Allocation 9GB

**Describe the bug**

**To Reproduce**
1. Go to Spawner
2. Break spawner
3. Watch things drop

**Expected behavior**
only vanilla exp to do

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
thanks, made spawners tougher. cant disable the drops tho
