### ISSUE TITLE
[BUG] Epic fight mod weapons cant get souls BETA 0.1.1

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#30]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.1
 - World Type Multiplayer
 - RAM Allocation 9GB

**Describe the bug**

Title

**To Reproduce**
1. Make a weapon
2. Drag soul to weapon
3. Soul doesnt bind

**Expected behavior**
That the soul binds

**Additional Information (screen shots, etc.)**

**Comment by DJGunn** [comment]
I can second this bug. I haven't tested every weapon, but so far it seems to only affect the Epic Fight Mod weapons in my experience.

I've encountered the issue with greatsword, spear, and dagger so far. Funnily, the dagger souls apply to the knives from the cooking mod and fishing mod. :P (just not the EFM dagger)

**Comment by mahjerion** [comment]
SEems to be an issue with the config on servers, works in sp

**Comment by mahjerion** [comment]
fixed
