### ISSUE TITLE
[BUG] Typing @ in JEI crashes the client

### ISSUE THREAD

**Issue by avicuz1142** [mahjerion/Craft-to-Exile-2-Resolution#31]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [0.1.1 beta]
 - World Type: singleplayer/LAN/multiplayer
 - RAM Allocation 8GB

**Describe the bug**
Trying to type @ (Shift + 2) In JEI crashing the client everytime

**To Reproduce**
1. Open JEI
2. Type @ in the search bar
3. Crash

**Expected behavior**
@ should be typed into the search bar without crashing

**Additional Information (screen shots, etc.)**
Add any other context about the problem here
[crash-2021-11-06_02.50.57-client.txt](https://github.com/mahjerion/Craft-to-Exile-2-Resolution/files/7487655/crash-2021-11-06_02.50.57-client.txt)
.

**Comment by avicuz1142** [comment]
Pressing W on create's blaze burner also crash the game aswell....

**Comment by mahjerion** [comment]
resolved
