### ISSUE TITLE
[MOD] Experience lock.

### ISSUE THREAD

**Issue by AetherMemes** [mahjerion/Craft-to-Exile-2-Resolution#33]
So me and my friend were fighting an entire pillager outpost, and like 2 minutes in we stopped getting experience, and i am not saying that stopping gaining experience is bad idea, its just that it happens too quickly, if it was after like say 15-20 minutes of fighting and killing, or the amount of times you CAN kill something should be increased wayy more, it is unbearably bad to have such limited experience gain, especially when mob spawning is all fucked up and most the time only 1 of a certain type spawns.

**Comment by mahjerion** [comment]
thanks for feedback, yes this is a wip and some ideas are being thrown around. good to know it too fast tho
