### ISSUE TITLE
Party Friendly Fire

### ISSUE THREAD

**Issue by AetherMemes** [mahjerion/Craft-to-Exile-2-Resolution#34]
Honestly, its exhausting to fight with someone side by side and just get smacked by your own team-mate, you guys are trying to kill an enemy and end up stunning/killing yourselves, i suggest that if the players are in some sort of party, there is atleast an option to turn off friendly fire, its just stupid in my opinion to have friendly fire between team-mates/

**Comment by mahjerion** [comment]
lol calling something stupid while giving feedback is not a good way to give feedback...

anyway there is a party function but if friendly fire is on whil ein a party then i can implement teams again like in dissonance
