### ISSUE TITLE
[BUG] Epic Fight Mod Skills lost on death

### ISSUE THREAD

**Issue by DJGunn** [mahjerion/Craft-to-Exile-2-Resolution#35]
**Technical Specs (please complete the following information):**
 - Craft to Exile Resolution 0.1.1
 - World Type Multiplayer
 - RAM Allocation 8 GB

**Describe the bug**
Epic Fight skills which are learned via book, are lost upon player death. I learned dodge, lost it when I died. I then learned guard and energized guard and lost both of those when I died as well.

**To Reproduce**
1. Learn an Epic Fight skill
2. Die
3. Attempt to use Epic Fight skill

**Expected behavior**
Death does not remove all learned Epic Fight skills

**Additional Information (screen shots, etc.)**
The Epic Fight skills GUI that you can open with a hotkey looks strangely empty. I've never used the mod so I'm not sure if this is intended.

**Comment by mahjerion** [comment]
skills should be properly disabled now, thanks
