### ISSUE TITLE
[BUG] MnS things are not dropping

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#43]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.1
 - World Type Multiplayer
 - RAM Allocation 9GB

**Describe the bug**
Mobs dont seem to be dropping MnS loot consistently

**To Reproduce**
1. Kill stuff
2. Get a few things
3. Kill more stuff
4. No MnS drops

**Expected behavior**
For MnS drops to consistently drop

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
seems to be an issue with favour not being disabled even tho it is

**Comment by ProvoGo** [comment]
having 0 favor still ruins the drop rate even after the changes you made. BETA 0.1.2

**Comment by ProvoGo** [comment]
closing this one since i made a new one for the 0.1.2 version

**Comment by ProvoGo** [comment]
closing this one since i made a new one for the 0.1.2 version
