### ISSUE TITLE
[BUG] Typing Tier 1/2/3/4 in JEI

### ISSUE THREAD

**Issue by LadyPari** [mahjerion/Craft-to-Exile-2-Resolution#45]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.1
 - World Type multiplayer
 - RAM Allocation 6gb

**Describe the bug**
Using the JEI search bar, when typing Tier 1, 2, 3, or 4, you immediately crash. Your MC will close out to the launcher. Similar to the @ bug but worse lol.

**To Reproduce**
1. Go to JEI
2. Click onto the search bar
3. Type Tier 1 or 2 or 3 or 4
4. See yourself crash AND an error at the launcher

**Expected behavior**
You don't crash and you see what you're looking for in the JEI.

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
This SHOULD be fixed in the next update but not sure, please confirm once i release it
