### ISSUE TITLE
[BUG] crossbow with hunting spells doesnt work

### ISSUE THREAD

**Issue by Iliakoss** [mahjerion/Craft-to-Exile-2-Resolution#46]
- Craft to Exile Resolution 0.1.1

I already understand you know hunting spells are a bit bugged but this is a different part of it. For spells that require a ranged weapon it only strictly considers bows as ranged weapons causing it to not allow you to cast the spells if using a crossbow. You can force it to work by going into creative so it likely is just a classification problem though. 

Good luck Mahj

1. spec into hunting arrow spells
2. have a Mine and Slash crossbow
3. attempt to use spells
4. sadness

**Comment by mahjerion** [comment]
should be fixed in the next update
