### ISSUE TITLE
[BUG] Quest rewards are one tier too high BETA 0.1.2

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#50]
**Technical Specs (please complete the following information):**
- Craft to Exile Version 0.1.2 
- World Type Multiplayer
- RAM Allocation 9GB

**Describe the bug**
Starter quests are giving tier 1 stuff (meaning lvl 10) instead of tier 0 stuff

**To Reproduce**
1. Complete quest
2. Claim rewards
3. See item with a higher tier

**Expected behavior**
The items should be one tier lower

**Additional Information (screen shots, etc.)**
![2021-11-08_20 43 00](https://user-images.githubusercontent.com/36768970/140807345-3290a899-0f9e-4cd4-ba0e-e88182aa1cba.png)
![2021-11-08_20 43 13](https://user-images.githubusercontent.com/36768970/140807352-0ef70231-db25-4b24-890e-770ef0ee4c85.png)

**Comment by mahjerion** [comment]
tier 1 should be 1-20 because tier 2 is 21-40

but even if it was tier 0 and tier 1, tier 1 would be 21-40 so not really sure whats goin on.

**Comment by ProvoGo** [comment]
wait so tier 0 isnt meant to exist? that would make sense since in the creative menu the tier 5 souls are actually tier 0
