### ISSUE TITLE
[BUG] Mine And Slash battle towers spawn in the void world BETA 0.1.2

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#51]
**Technical Specs (please complete the following information):**
- Craft to Exile Version 0.1.2 
- World Type Multiplayer
- RAM Allocation 9GB

**Describe the bug**
Mine And Slash battle towers spawn in the void world

**To Reproduce**
1. Go to void world
2. See battle tower

**Expected behavior**
That they dont spawn in the void

**Additional Information (screen shots, etc.)**
![2021-11-08_23 56 23](https://user-images.githubusercontent.com/36768970/140831648-49816af8-e0f7-4b7e-9c70-45d8c41d4417.png)

**Comment by mahjerion** [comment]
removed void
