### ISSUE TITLE
[BUG] Cannot kill Barnacle (sea monster) with epic fight mod melee

### ISSUE THREAD

**Issue by DJGunn** [mahjerion/Craft-to-Exile-2-Resolution#52]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type Multiplayer
 - RAM Allocation 8 GB

**Describe the bug**
Epic Fight Mod appears to only allow you to attack directly in front of you to avoid cheesing enemies with dirt towers; however the barnacle enemy attacks from below, grapples you, and pulls you down, and even once it hits the ocean floor it clips into the blocks below you. Even though you can look and aim down, all of your attacks swing out directly in front of you. I haven't tried it with a ranged weapon, but with a melee weapon, its a OHK on players.

**To Reproduce**
1. Go to the ocean
2. Get on a boat and equip melee weapon
3. Get grabbed by a barnacle
4. Frantically try to chop yourself free but die instead as your blows hit air in front of you :P

**Expected behavior**
This is technically expected behavior, but likely not intended and should probably be addressed in some way :P

**Additional Information (screen shots, etc.)**
Was too busy screaming and drowning to take a picture :P

**Comment by DJGunn** [comment]
Update:

I got grabbed by a barnacle a few minutes ago while I had water breathing. I could not kill it, and it could not drown me. I was unable to hurt it in any way, and its attack speed got faster and faster. In the span of 20 or so seconds, it broke my helmet, my legs, my boots and my necklace, and one ring. I was barely able to unequip my rings and my chest piece. My chest piece only survived because it was a netherite chest piece someone gave me that was a random drop someone didn't need and i put a soul on it.

I'm currently in a position where I'm soft-locked from playing the game, as my only equipment is a chest piece, a dagger, a shield, and two rings, and I while I have the materials to craft minecraft items, I don't have any souls or armor crafting reagents. All of my gear was iron except for my chest piece and dagger, and everything was at full durability as I was just leaving to go on a quest.

It seemed as though the Barnacle was attacking 3-5 times a second, and because its below you, you can't hit it with epic fight mod.

Thanks

**Comment by mahjerion** [comment]
thanks, fixed
