### ISSUE TITLE
[BUG] Paintings now appears invisible

### ISSUE THREAD

**Issue by LadyPari** [mahjerion/Craft-to-Exile-2-Resolution#53]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type multiplayer
 - RAM Allocation 6gb

**Describe the bug**
I have paintings on the wall and they're invisible now. You can place them down and pick them back up but the paintings themselves are completely transparent now.

**To Reproduce**
1. Place painting 
2. Admire the transparency

**Expected behavior**
A painting that covers things.

**Additional Information (screen shots, etc.)**
![with painting](https://user-images.githubusercontent.com/93747436/140840146-21cc8c22-aa3e-4ad0-afc2-6b34f95a3372.png)
![without painting](https://user-images.githubusercontent.com/93747436/140840148-6486b650-1adb-4791-bfcc-06610274641b.png)

**Comment by mahjerion** [comment]
fixed thanks!
