### ISSUE TITLE
[Suggestion] Add quest to explain Orb of Transmutation and similar mechanics

### ISSUE THREAD

**Issue by DJGunn** [mahjerion/Craft-to-Exile-2-Resolution#54]
**Is your feature request related to a problem? Please describe.**
There are mechanics in the game that are also present in Dissonance, that players migrating to the CTE 2 will already be familiar with. These mechanics should have quests related to them so new players can know about them as well!

**Describe the solution you'd like**
Addition of quests teaching new players about mechanics that may otherwise be obvious to veterans of CTE, such as Orb of Transmutation (which I just learned about from provo!)

**Describe alternatives you've considered**
I'm not sure which other mechanics could use tutorials as I don't know which mechanics I don't know, heheh.

**Additional context**
N/A

Thanks!

**Comment by mahjerion** [comment]
yup it's coming! thanks for posting to remind me though haha i probably would have forgotten about these orbs for a while
