### ISSUE TITLE
[BUG] Uncommon Essence 

### ISSUE THREAD

**Issue by LadyPari** [mahjerion/Craft-to-Exile-2-Resolution#55]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type Multiplayer
 - RAM Allocation 6gb

**Describe the bug**
The description is highly misleading and leads to the items being yeeted to oblivion.

**To Reproduce**
1. Have 9 Uncommon Essences
2. Right click it when you have 9
3. Have it all disappear and you have nothing left

**Expected behavior**
Apparently you're supposed to salvage these essences and then gather the by-product to a stack of 9 before combining. Not the essence themselves as the description says.

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/93747436/141012096-a876322c-2fed-4ea6-91b7-37ee5e7d8108.png)

**Comment by mahjerion** [comment]
weird, works for me o.o
