### ISSUE TITLE
[BUG] Better end has replaced the elytra ship generation BETA 0.1.2

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#58]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type Multiplayer/Singleplayer
 - RAM Allocation 9GB

**Describe the bug**
Vanilla end ships has been replaced with the end ships from better end, but since better end is not in the pack it just result in half the ship missing. Which also means its impossible to get an elytra currently

**To Reproduce**
1. Go to an end city
2. See messed up end ship

**Expected behavior**
I expected the vanilla end ships to spawn since better end was removed

**Additional Information (screen shots, etc.)**
this is NOT and artifact from using an old world, fresh world with the 0.1.2 update
![](https://cdn.discordapp.com/attachments/733797677036339233/908117887477248081/2021-11-10_23.16.03.png)

**Comment by mahjerion** [comment]
fixed in update
