### ISSUE TITLE
[BUG] Can't place colony in Void World.

### ISSUE THREAD

**Issue by Jargonecius** [mahjerion/Craft-to-Exile-2-Resolution#60]
**Technical Specs (please complete the following information):**
 - Version: Resolution 0.1.2
 - World Type: Official Server

**Describe the bug**
Tried to place my townhall in my void dimension and was given an error code.

**Expected behavior**
Expected to be able to place my townhall there since that's what the world is apparently for.

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
thanks, will be removing void as i have another sol'n
