### ISSUE TITLE
Gear breaking problems

### ISSUE THREAD

**Issue by avicuz1142** [mahjerion/Craft-to-Exile-2-Resolution#62]
**Is your feature request related to a problem? Please describe.**
At the moment your mine and slash gears just breaks like vanilla and vanished forever and sometime not having a chance to repair them

**Describe the solution you'd like**
Gears should just stay at 0 durability/broken and not providing stats anymore instead of just breaking

**Describe alternatives you've considered**

**Additional context**

**Comment by RobertSkalko** [comment]
Can you explain what you mean by 

>sometime not having a chance to repair them

Do your gears not last a few minutes of mob killing? Do you know about using dusts to repair them? Do you enchant them with unbreaking?

I have an idea. I can make it so the higher the rarity, the more extra durability an item gets. This would make it harder to accidentally break an item the better it actually is.

**Comment by avicuz1142** [comment]
> Can you explain what you mean by
> 
> > sometime not having a chance to repair them
> 
> Do your gears not last a few minutes of mob killing? Do you know about using dusts to repair them? Do you enchant them with unbreaking?
> 
> I have an idea. I can make it so the higher the rarity, the more extra durability an item gets. This would make it harder to accidentally break an item the better it actually is.

Like if they breaks they're gone forever that you don't have a chance to repair them anymore especially with items in curios slots that we don't often check their durability until they disappear and well damage over time breaks those gear in extreme fast speed. Making them stay at 0 durability instead of breaking entirely would be much user friendly, imagine putting all your efforts to make a top tier item and its gone forever just only when you forgot to check their durability every second/took too much dot damage.

**Comment by mahjerion** [comment]
this should be improved in the next update, but they are not indestructible, thanks for feedback!
