### ISSUE TITLE
[BUG] Spells dont work in the blue skies dimensions BETA 0.1.2

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#64]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type Multiplayer
 - RAM Allocation 9GB

**Describe the bug**
You cant use spells in the blue skies dimensions, relogging doesnt fix it either

**To Reproduce**
1. Go to a blue skies dimension
2. Try to use a spell
3. See that it doesnt work

**Expected behavior**
That you can use spells in the blue skies dimensions

**Additional Information (screen shots, etc.)**
doesnt work in singleplayer either, but you can cast spells if you are in creative mode

**Comment by mahjerion** [comment]
duplicate of #41

**Comment by ProvoGo** [comment]
closing it since its a duplicate, no need to clutter the issue tracker
