### ISSUE TITLE
[BUG] Restriction on certain items doesnt work

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#65]
After reaching the next tier (tier 1) which is restricted to lvl 21, i was able to use items of that tier, that were supposed to be usuable after reaching lvl 26.
![2021-11-16_02 49 33](https://user-images.githubusercontent.com/7965035/141881263-427816b9-cbc0-40fe-ac88-7f0237c55841.png)

**Comment by mahjerion** [comment]
item level isnt restriction, it's the level: 21, which you are
