### ISSUE TITLE
[BUG] When favor reaches 0 mns things dont drop BETA 0.1.2

### ISSUE THREAD

**Issue by ProvoGo** [mahjerion/Craft-to-Exile-2-Resolution#66]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.1.2
 - World Type Multiplayer
 - RAM Allocation 7GB

**Describe the bug**
Title

**To Reproduce**
1. Kill things to reach 0 favor
2. Stop getting drops

**Expected behavior**
I expect things to drop since the favor part of mns should be disabled

**Additional Information (screen shots, etc.)**
I'm not 100% sure that its consistent that it happens right when you hit 0 favor, but i have yet to see a player on the official server still get drops when they are at 0 favor

**Comment by mahjerion** [comment]
should be fixed for next release
