### ISSUE TITLE
[Quality of life] - Extract souls out of equipment

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#68]
The souls provide a real good way to make every single piece of armor valuable throughtout the game. Its an awesome feature and a huge improvement coming from dissonance.

The variety of different armors on the other hand provide another problem. E. g. you have put a great, maybelegendary soul into an iron helmet, just to get your hands on a diamond or netherite helmet, you would really want to be able to switch that soul over to the other helmet. Especially since different  items might provide awesome passives you wouldnt want to miss.

Therefore i would suppose to introduce some kind of tool, that is able to split the soul from an item or a station which transfers a soul between 2 items. Maybe even at a slight cost.

**Comment by ProvoGo** [comment]
https://github.com/RobertSkalko/Mine-and-Slash/issues/312

**Comment by Ikarobus** [comment]
> [RobertSkalko/Mine-and-Slash#312](https://github.com/RobertSkalko/Mine-and-Slash/issues/312) bit of a different scenario but i think roberts response would be the same

I think both together would work really well. It might be that you have an (identified) soul, which you put onto an item just to get a better item later. Wouldn't be the world, but still quite the QoL.

**Comment by mahjerion** [comment]
the new common soul kind of supports this, think its the closest we'll get
