### ISSUE TITLE
Add Age of Exile loot to the loot table

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#69]
If its not already planned, there should be mine and slash loot added to the loot table. Its kinda disappointing to only be able to find the lackluster vanilla standard loot in every chest.

**Comment by mahjerion** [comment]
good idea, i'll have to see if robert can do something about this becuase it would take quite a bit of work on my end.

**Comment by mahjerion** [comment]
actually nvm not that hard, done
