### ISSUE TITLE
[BUG] Epic Fight Mod Friendly Fire

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#71]
When in an FTB Team and Age of Exile party, you wont be able to damage your teammates via age of exile spells and skills. You are on the other hand still able to hit and damage you teammates with Epic fight melee attacks.

**Comment by mahjerion** [comment]
you'll need to use vanilla teams too, i have it enabled on the server atm but it will be enabled by default in the next udpate as well for non-official server players
