### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#72]
Current Server Version (also affects single player)

Mod: Simple Storage Solutions:

The mod provides the ability to create storage system. The storage system can be accessed via a remote. Taking stuff out of the storage /putting stuff in there via the remote works properly. 

There is also another remote like item. If linked to the storage and held in your inventory it will autimatically put everything you pick up into the linked storage (item name: Network collector remote).

The Bug: 

Items picked up while in possession of an active network collector remote will disappear and neither be added to the players nor the linked networks inventory.

**Comment by mahjerion** [comment]
thansk for the report

**Comment by Ikarobus** [comment]
np i might have a few more

**Comment by mahjerion** [comment]
disbaled
