### ISSUE TITLE
[MOD] Relics 

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#75]
https://www.curseforge.com/minecraft/mc-mods/relics-mod/files

https://github.com/SSKirillSS/relics/wiki/Relics-description

After browsing through the different mods, I came to realise that the options of relics seem to be very limited right now.

I just stumped upon this mod which adds a lot of unique relics with some very strong and some very fun abilities, which may need to fine tuning for compatibility with mine in Slash. But if this can be done, the different relics may provide some very interesting options for different playstyles, tactics and roleplay.

**Comment by mahjerion** [comment]
hm, checked it out. seems interesting but some of these effects just wouldnt work. ill consider it later

**Comment by mahjerion** [comment]
prob not, thanks for suggestion
