### ISSUE TITLE
[MOD] Loot Beams

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#76]
https://www.curseforge.com/minecraft/mc-mods/loot-beams

I think this mod would highly add to the hack and slash experience the game aims for, It will basically highlight ground items with different color beams depending on rarity. Making rare drops more exiting.

**Comment by mahjerion** [comment]
have you tried it by any chance? last time i tried it didnt actually work with mine and slahs, not sure if its changed by now
