### ISSUE TITLE
[MOD] Epic Knights Mod

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#77]
https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons

This mod adds a variety of armors, weapons and shields to the game. All with build in compatibility with the epic fight mod. Seems to really fit well with the modpack and adds a bit of variety.

**Comment by mahjerion** [comment]
Would be pretty cool. I can see myself adding this much later though. Want to get things working properly first!
