### ISSUE TITLE
[BUG] Dagger not cost energy when fighting, souls not work on daggers and spells have no damage when held dagger

### ISSUE THREAD

**Issue by MAGXENO** [mahjerion/Craft-to-Exile-2-Resolution#79]
**Technical Specs (please complete the following information):**
 - Craft to Exile Resolution 0.2.0
 - World Type Multiplayers
 - RAM Allocation 6GB

**Describe the bug**
All of the dagger weapon, include stone dagger, iron dagger, gold dagger, diamond dagger and netherite dagger not cost energy bar when using, and not supported by soul additions. Also, the spells do no damage.

**To Reproduce**
1. Craft any dagger above
2. Click to change mining mode to epic fight mode
3. Find a zombie to kill. Doing the damage without cost energy.
4. At the same time, 5 vanilla damage dagger with 2 damage addition soul can do only 1/5 damage than a common sword with 6 vanilla damage with 1 damage soul. Seems like the soul is not work on the dagger. Also, with the dagger and use a spell, but spell do no damage

**Expected behavior**
Dagger should work as other type weapons: Cost energy bar when using, soul addition can work on the dagger, spells have damage

**Additional Information (screen shots, etc.)**
N/A

**Comment by mahjerion** [comment]
This is on a server right?

**Comment by mahjerion** [comment]
Tested, dagger works fine. Not sure how to replicate. Are you sure you're on 0.2.0?

**Comment by mahjerion** [comment]
fixed the issue where they mnight do 0 damage tho
