### ISSUE TITLE
Craft Legendary Souls

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#85]
Suggestion: 

If you combine 9 Legendarys of the same tier you get 1 Soulstone. Combining 1 Soulstone with a golden Item (e.g. Helmet) will give you a legendary soul of the same tier for the same itemtype.

**Comment by mahjerion** [comment]
i dont intend on adding craftable souls besides the common one, also legendary is not a rarity

i will be adding ways to get higher rarity souls though like via dungeon and quests
