### ISSUE TITLE
[BUG] Fish in the END give EXP and Loot

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#86]
![2021-12-07_00 12 04](https://user-images.githubusercontent.com/7965035/144937615-c3705cbd-d974-4bd0-a7a1-0156bdb198bb.png)
![2021-12-07_00 12 39](https://user-images.githubusercontent.com/7965035/144937663-93cd49be-268f-4030-aeca-9dd916054ed2.png)

Fishes in the END give full loot and exp. They also have way lower health then endermen. Whilew testing i could get 1 level within 10/15 minutes (around lvl 30)

**Comment by mahjerion** [comment]
Fantastic thanks fo rletting me know. Any chance you know which mod these fish are from?

**Comment by RobertSkalko** [comment]
Someone marked their fish as hostile mobs somehow probably

**Comment by Ikarobus** [comment]
It should be better end reforged. Can't hop on to play. But I'm 99% sure

**Comment by mahjerion** [comment]
Yeah the betterX mods were ported, not done so perfectly, thanks!

**Comment by mahjerion** [comment]
fixed for nex tupdat
