### ISSUE TITLE
[BUG] Identify Tomes try to reveal souls that are already revealed.

### ISSUE THREAD

**Issue by Ikarobus** [mahjerion/Craft-to-Exile-2-Resolution#87]
![2021-12-07_00 16 04](https://user-images.githubusercontent.com/7965035/144937980-e9d1e290-6dc5-4dad-a0c1-25c796d51af9.png)
Identify Tomes can be used to reveal souls (so you can see the item it would generate).
You can reveal the same soul multiple times rerolling the stats.

**Comment by mahjerion** [comment]
oh wow seems like big bug, thanks for reporting this

**Comment by mahjerion** [comment]
fixed for nex update
