### ISSUE TITLE
Illiger Fort Too much loot?

### ISSUE THREAD

**Issue by Quack-a** [mahjerion/Craft-to-Exile-2-Resolution#89]
I was doing an Illiger fort and noticed an absurd amount of loot this is the loot from about half of the fort with 40% magic find if that matters. This probably destroys loot progression. inside the backpack is 1000 emeralds and about 6 totems of undying if that matters.
![loot](https://user-images.githubusercontent.com/95458427/144971999-006977f4-2657-4512-beaf-c74f1fdb9360.PNG)

**Comment by mahjerion** [comment]
should be fixed next update thanks for letting me know
