### ISSUE TITLE
[BUG] Flame Weapon has no damage scaling

### ISSUE THREAD

**Issue by Quack-a** [mahjerion/Craft-to-Exile-2-Resolution#90]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 0.2.1
 - World Type Multiplayer
 - RAM Allocation 8gb

**Describe the bug**
Flame weapon skill's damage seem to be stuck at level 1 have not tested ice or poison but they might be as well.

**To Reproduce**
Level Flame weapon to any level past 1
Activate skill
Hit mob
deal between 6-11 fire damage in Flame weapon's case at max level

**Expected behavior**
activate skill
hit mob
deal 30-40 fire damage

**Additional Information (screen shots, etc.)**
Hard to screenshot damage numbers any advice?

**Comment by RobertSkalko** [comment]
And what's your damage at lvl 1 spell?

**Comment by Quack-a** [comment]
10 fire damage on level 1 mob

**Comment by RobertSkalko** [comment]
That spell has scaling of 0.4F to 0.75F. So if it does 10 dmg at lvl 1, should do bit less than 20 dmg at maximum level. 
I have tested and it works fine on my end.

**Comment by Quack-a** [comment]
weird could just be the damage numbers displayed on the skill in the window are off then or maybe mob resistance. It is just kind of confusing when it says 30 extra fire damage and I only do like 8-10 extra

**Comment by mahjerion** [comment]
It's the damage numbers, they're technically wrong.

**Comment by RobertSkalko** [comment]
Edit you're right, I thought you meant flame strike. Will check it out

**Comment by RobertSkalko** [comment]
Fixed
